### ISSUE TITLE
Do I have to go through the verification and manual log in process every day after access token expires at midnight?

### ISSUE THREAD

**Issue by emsensing** [jessecooper/pyetrade#100]
Do I have to go through the verification and manual log in process every day after access token expires at midnight?
Is there a way to keep using the same token and token secret without need to verify manually again and again?
Will the renew access token help?

# Setting up the object used for Access Management
authManager = pyetrade.authorization.ETradeAccessManager(
    consumer_key,
    consumer_secret,
    tokens['oauth_token'],
    tokens['oauth_token_secret']
)

# Triggering a renew
authManager.renew_access_token()

**Comment by Robert-Zacchigna** [comment]
Yes, unfortunately you do. This is how Etrade has setup the API, which is not ideal (as you have outlined).

The work around is to setup your own automation to go through the login flow and retrieve/refresh your tokens that way (that's what i do).

You can use popular packages such as **playwright** or **selenium** to automate this process.

Its not ideal to have to use a headless browser to do this but unfortunately, there is no other way to do it (at least none that i have found).

Hope this helps.

**Comment by emsensing** [comment]
> Yes, unfortunately you do. This is how Etrade has setup the API, which is not ideal (as you have outlined).
> 
> The work around is to setup your own automation to go through the login flow and retrieve/refresh your tokens that way (that's what i do).
> 
> You can use popular packages such as **playwright** or **selenium** to automate this process.
> 
> Its not ideal to have to use a headless browser to do this but unfortunately, there is no other way to do it (at least none that i have found).
> 
> Hope this helps.

Thanks for replying. That's what I figured. Have to do some web automation.
