### ISSUE TITLE
Issues Implementing

### ISSUE THREAD

**Issue by dancassin** [jessecooper/pyetrade#14]
Hey everyone,

I'm a bit new to python, but not new working with APIs. For some reason I'm having issues getting this to work. Would someone mind posting an example file?

Thanks!

**Comment by 1rocketdude** [comment]
Have a look at https://github.com/1rocketdude/pyetrade_option_chains

That will show basic option chains stuff.
I have tons of code that I’m happy to share. Send me a note about what you’re actually trying to do.

“Know the truth and it shall set you free” (John 8:32)

**Comment by dancassin** [comment]
something really simple. Just the beginning of the python file, importing, logging in to etrade, maybe a stock history, and making a buy market order.

I've tried the "Example Usage" code on the main pyetrade page, but I'm still not sure what the 'token' portion is, and all the code ran and returned nothing.
