### ISSUE TITLE
change existing orders

### ISSUE THREAD

**Issue by hz2018tv** [jessecooper/pyetrade#15]
hi, can we change existing orders directly? I know it can be done by canceling the old ones and place new ones. ETRADE API doc seems to have <orderId>/change/place.

**Comment by jessecooper** [comment]
This is definitely an area that needs some work and is listed out in the https://github.com/jessecooper/pyetrade/blob/master/pyetrade/order.py TODOs. Contributions are always welcome as I do not at the moment have any timeline on when I will be able to implement this.

**Comment by hz2018tv** [comment]
I did give it a shot, but got service not available, so not sure if it is doable, even it is listed in their docs.

**Comment by jessecooper** [comment]
What was the error? If you would like we can use this thread to try and troubleshoot the issue your having. Do you have a fork with a branch with these changes? I would be willing to take a look.

**Comment by hz2018tv** [comment]
I did not fork a branch. just some quick hacks to see how it goes. 

In the preview function, I added an "orderNum"=order_id in the "order" section. then got Response status_code=405. sub error code=9999. I guess these mean "service not available".
In the order placing function,  change the url to /v1/accounts/<accnt_id>/orders/<order_id>/change/place, got error_code=9999.

**Comment by jessecooper** [comment]
Are you using a PUT or a POST? that might be the issue.

**Comment by hz2018tv** [comment]
that is it!  passed with put.

**Comment by hz2018tv** [comment]
so, regarding modifications to pyetrade, it is up to you to add new functions for preview_change and place_change or add if..else in the existing functions. please let me know if I can help. thanks again.

**Comment by jessecooper** [comment]
It sounds like it might just make a good param with if/else but it really could go either way. Ill leave it up to you as the implementer to decide what would be the cleanest implementation. I would look at the params and see if it make sense as just a param or if it would be better as a method(s) given the args it takes are different enough to warrant its own method.

**Comment by hz2018tv** [comment]
Sorry, didnt see email notifications on this till this weekend. please review the pull request. Thanks
