### ISSUE TITLE
More of a general Inquiry (Consumer key and secret key)

### ISSUE THREAD

**Issue by Nswaich177** [jessecooper/pyetrade#20]
Love this entire collection! Where would I get a consumer/secret key? I'm relatively new to API's, but was trying to implement this module into a personal project. Any help would be great! 

Thanks

**Comment by 1rocketdude** [comment]
You've got to get them both from eTrade. Make sure you are specific that you are looking for a trading pair, not the sandbox pair.

It takes 3-5 days - given the current situation, I would not be surprised if it took twice as long. Everything takes longer now.

**Comment by windrider09** [comment]
I just went through the production key request, I got a response with two
days. Instructions can be found here:
https://developer.etrade.com/home
-- 
-j
