### ISSUE TITLE
Using the get_quote only returns GOOGL

### ISSUE THREAD

**Issue by Nswaich177** [jessecooper/pyetrade#22]
Regardless of the parameters I input (detail flag, symbols), it only returns "All" for GOOGL. 

market = pyetrade.ETradeMarket(
    consumer_key,
    consumer_secret,
    tokens['oauth_token'],
    tokens['oauth_token_secret'],
    dev = True
)

symbols = ['PETS']
r = market.get_quote(symbols, detail_flag="fundamental")

**Comment by 1rocketdude** [comment]
I want to say that it should be:

market = pyetrade.market.ETradeMarket(consumer_key,
consumer_secret,
tokens['oauth_token'],
tokens['oauth_token_secret'],
dev = False
)

The call to get_quote() appears correct.
Have you tried bypassing the pyetrade API and just using straight http request by forming your own request from scratch? It is not unheard of for the eTrade API to be inaccurately applied.

**Comment by Nswaich177** [comment]
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url:
https://api.etrade.com/v1/market/quote/PETS

This is what I get when I set dev to False. Any idea what this permission issue could be?

**Comment by mkfrancis01** [comment]
> requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url:
> https://api.etrade.com/v1/market/quote/PETS
> 
> This is what I get when I set dev to False. Any idea what this permission issue could be?

You need to connect into the production environment using production authorization keys and credentials to use the url below. Thats why you are getting an 'unauthorized for url" error 
https://api.etrade.com/v1/market/quote/ticker

For sandbox (developer) environment you get connected using the url below
https://apisb.etrade.com/v1/market/quote/ticker
In sandbox the only quote that is fetched is GOOGLE and this is simply just a limitation of the  functionalities/options available in developer mode. Use sandbox for testing your code before deploying to production
