### ISSUE TITLE
Need help: preview request works but cannot place order

### ISSUE THREAD

**Issue by yangliu2** [jessecooper/pyetrade#23]
First, I tried using your pyetrade package but not be able to place order. 
Then I tried to use the Etrade provided sample code, but I got this error.

`{'code': 101,
  'message': '{com.etrade.api.v1.order.InvalidPreviewId}'` 

The second time I tried though, I got a different error. 
`{'code': 101,
  'message': 'For your protection, we have timed out your original order request. If you would like to place this order, please resubmit it now.'}`

Payload I sent is like this: 
```
                   <PlaceOrderRequest>
                       <orderType>EQ</orderType>
                       <clientOrderId>5340619102</clientOrderId>
                       <previewIds>
                           <previewId>1627181131</previewId>
                           <cashMargin>CASH</cashMargin>
                       </previewIds>
                       <Order>
                           <allOrNone>false</allOrNone>
                           <priceType>LIMIT</priceType>
                           <orderTerm>IMMEDIATE_OR_CANCEL</orderTerm>
                           <marketSession>REGULAR</marketSession>
                           <stopPrice></stopPrice>
                           <limitPrice>100</limitPrice>
                           <Instrument>
                               <Product>
                                   <securityType>EQ</securityType>
                                   <symbol>GOOG</symbol>
                               </Product>
                               <orderAction>BUY</orderAction>
                               <quantityType>QUANTITY</quantityType>
                               <quantity>1</quantity>
                           </Instrument>
                       </Order>
                   </PlaceOrderRequest  >
```

I hate that Etrade makes me preview order before placing one, but I see that pyetrade also need to preview order before placing it. If you seen this before, any help is appreciated. 
If you can give me some code example of how to use pyetrade to preview and place order, I would also much prefer doing it that way. I'm kinda reading challenged when reading documentations without code examples. Thanks!

**Comment by mkfrancis01** [comment]
Hello yangliu2. I am also having the same issue. Matter of fact I am not even able to execute the preview_equity_order() function. Getting "missing kwargs" error. Below are the details. Hope I am not hijacking your issue request but would you know what is causing this issue since I see you are able to execute preview_equity_order?

**if not all(param in kwargs for param in mandatory):**
--> 135 raise OrderException
136
137 if kwargs["priceType"] == "STOP" and "stopPrice" not in kwargs

Below is the kwargs dictionary I am using in SandBox environment
kwargs = {
"accountId":"6_Dpy0rmuQ9cu9IbTfvF2A",
"symbol":"AAPL",
"orderAction":"BUY",
"clientOrderId": random.randint(10000000,99999999),
"priceType":"MARKET",
"allOrNone": True,
"limitPrice":0,
"stopPrice":0,
}

**Comment by yangliu2** [comment]
No problem man! I'm having the same error. I manually checked the required keys AND modified source code to check is mandatory have it. No luck. I don't know what's it's checking. This is where I went to Etrade sample code instead. Also remember trade sandbox have fixed response for preview and place order, so you need to make sure your placing order payload is the same as the preview response, not whatever payload you send it to them. Now I'm sticking on error 9999 for placing order.

**Comment by mkfrancis01** [comment]
Hello yangliu2

Thanks for your response. After trying a few things was able to make the preview order and place order to work. You simply have to make sure your kwargs dictionary is in the order in the mandatory list in the check order() function.

mandatory = ["accountId","symbol","orderAction","clientOrderId","priceType","quantity","orderTerm","marketSession"]
       
Ofcourse remember to use **  before kwargs in the paranthesis to show its a dictionary. 

All this was in dev environment. I haven't tried actual prod environment..

Let me know how it goes.

**Comment by mkfrancis01** [comment]
Test these kwarg keys values,

kwargs = {"accountId":"6_Dpy0rmuQ9cu9IbTfvF2A",
          "symbol":"GOGL",
          "orderAction":"BUY",
          "clientOrderId": random.randint(10000000,99999999),
          "priceType":"MARKET",
          "allOrNone": True,
          "limitPrice":0,
          "stopPrice":0,
          "quantity":100,
          "orderTerm":"GOOD_FOR_DAY",
          "marketSession":"REGULAR"
         }

Then after you instantiate the ETradeOrder class and create an object try calling the method below
myfirstorder.preview_equity_order(**kwargs_sell)

**Comment by yangliu2** [comment]
For some reason, if I use `resp_format='json'`, then I get a 400 response error. Without the parameter, it seems to be fine. `¯\_(ツ)_/¯`

**Comment by 1rocketdude** [comment]
The JSON response works for only about half of the API. This is not documented and it has been discovered by trial and error. Numerous tickets have been submitted and we’ve talked to the “API team”, but it’s been many years, so I doubt it will ever be fixed.

The XML format (default) seems to be consistently functional.

**Comment by gargv6880** [comment]
Hello yangliu2,

I am also facing exact same issue which you faced. Please let me know how you resolved this.

Thanks a lot.

**Comment by tommyhuangli** [comment]
Hi, @yangliu2 were you able to resolve this and place order successfully from python code?

**Comment by yangliu2** [comment]
I gave up on the idea, since my model wasn't able to outperform the "buy
and hold strategy" over 6 months. I did got some code from etrade support
several months later, but didn't even bother trying.

**Comment by yui410122** [comment]
I am also trying to place an order with the ETrade API and got the following error:

{'code': 101, 'message': 'For your protection, we have timed out your original order request. If you would like to place this order, please resubmit it now.'}

the preview order seems to be working ok. If anyone figures how to successfully place an order please let me know, thanks!

**Comment by yui410122** [comment]
@yangliu2 could you please share the code ETrade support provides? 

Thanks!

**Comment by tommyhuangli** [comment]
I have the extract same issue. Looks like E*TRADE is limiting the
individuals to do things like this.

**Comment by yangliu2** [comment]
Here is the code I got from Etrade. There weren't any formating, so you may have to retype. 
```
Below is a simple method for place order. Make sure you copy the fields from preview order into your place order and you have to pass the previewId from the response from the preview order into the place order request or it will not work. Should you questions feel free to reply to this message.

def place_order(session, account, order):

"""

Calls place order API to submit an order request for confirmation after preview order is successfully called

:param session: authenticated session

:param account: information on selected account

:param order: list of instruments from previous orders

"""

URL for the API endpoint
url = "https://api.etrade.com/v1/accounts/" + account["accountIdKey"]+ "/orders/place.json"
Add parameters and header information
headers = {"Content-Type": "application/xml", "consumerKey": config["DEFAULT"]["CONSUMER_KEY"]}
Add payload for POST Request
payload = """
{0}
{1}
{2}
false
{3}
{4}
REGULAR
{5}
{6}
{7}
{8}
QUANTITY
{9}
"""
payload = payload.format(order["order_type"], order["client_order_id"], order["preview_id"],
order["price_type"], order["order_term"], order["limitPrice"],
order["security_type"], order["symbol"], order["order_action"], order["quantity"])
Make API call for POST request
response = session.post(url, header_auth=True, headers=headers, data=payload)
logger.debug("Request Header: %s", response.request.headers)
logger.debug("Request payload: %s", payload)
Handle and parse response
if response is not None and response.status_code == 200:
parsed = json.loads(response.text)
logger.debug("Response Body: %s", json.dumps(parsed, indent=4, sort_keys=True))
data = response.json()
print("\nOrder number #"
+ str(data["PlaceOrderResponse"]["OrderIds"][0]["orderId"])
+ " successfully placed.")
else:
Handle errors
data = response.json()
if 'Error' in data and 'message' in data["Error"]and data["Error"]["message"]is not None:
print("Error: " + data["Error"]["message"])
else:
print("Error: Preview Order API service error")
```

**Comment by yui410122** [comment]
Thanks @yangliu2 !

"Make sure you copy the fields from preview order into your place order and you have to pass the previewId from the response from the preview order into the place order request or it will not work."

This comment is really useful! I tried to include the previewID and now placing the order works! 

Thanks a lot!

**Comment by jessecooper** [comment]
@yangliu2 Can you please open a PR with any changes that are needed in pyetrade to better support this?

**Comment by alanoatwork** [comment]
> Thanks @yangliu2 !
> 
> "Make sure you copy the fields from preview order into your place order and you have to pass the previewId from the response from the preview order into the place order request or it will not work."
> 
> This comment is really useful! I tried to include the previewID and now placing the order works!
> 
> Thanks a lot!

I tried including the previewId in the order but I still get error 400.  Any clue why this isn't working??

       resp = orders.preview_equity_order(
            accountId=self.account_id,
            symbol="IBM",
            orderAction="BUY",
            clientOrderId="1",
            priceType="MARKET",
            quantity="1",
            orderTerm="GOOD_UNTIL_CANCEL",
            marketSession="REGULAR"
        )

        preview_id = resp['PreviewOrderResponse']['PreviewIds']['previewId'].get_cdata()

        resp = orders.place_equity_order(
            previewId=preview_id,
            accountId=self.account_id,
            symbol="IBM",
            orderAction="BUY",
            clientOrderId="1",
            priceType="MARKET",
            quantity="1",
            orderTerm="GOOD_UNTIL_CANCEL",
            marketSession="REGULAR"
        )

**Comment by Lucifer-lab74** [comment]
I've tried all of above solutions but None is working for me, place order keep responding same error and preview order working correctly

**Comment by Robert-Zacchigna** [comment]
For anyone else who comes across this thread, i was unable to get the `preview_equity_order` and `place_equity_order` functions to work but i was able to come up with this workaround. 

You basically need to make the request yourself using the underlying api endpoints instead of the functions. For these function to work, you need to have already setup pyetrades oauth obj (in my case its `etrade_oauth`)
```python
import json
import xmltodict
import xml.etree.ElementTree as ET

from dicttoxml2 import dicttoxml

from pyetrade.order import ETradeOrder
from pyetrade import ETradeAccounts, ETradeOAuth
```
Function for making the post requests to the etrade api endpoints
```python
def _post_etrade_req(etrade_oauth: ETradeOAuth, etrade_order: ETradeOrder, account_id_key: str,
                     order_params: dict, post_endpoint: str, print_payload: bool, print_response: bool) -> dict:

    order_payload = dicttoxml(order_params, root=False, attr_type=False).decode('UTF-8')

    if print_payload:
        pretty_xml = ET.XML(order_payload)
        ET.indent(pretty_xml)
        print(f'\n{post_endpoint.capitalize()} Order Request XML Payload:\n{"="*(27+len(post_endpoint))}\n'
              f'{ET.tostring(pretty_xml, encoding="unicode")}')

    headers = {"consumerKey": etrade_oauth.consumer_key, 'Content-Type': 'application/xml'}
    post_endpoint_url = f'https://api.etrade.com/v1/accounts/{account_id_key}/orders/{post_endpoint}'

    order_response = etrade_order.session.post(post_endpoint_url, headers=headers, data=order_payload)

    order_data = json.loads(json.dumps(xmltodict.parse(order_response.text)))
    
    if print_response:
        print(f'\n{post_endpoint.capitalize()} Order JSON Response:\n{"="*(21+len(post_endpoint))}\n'
              f'{json.dumps(order_data, indent=4)}')

    return order_data
```

My `preview_shares_order` function - this returns the preview_order_params and the preview_id from the preview_order_response:
```python
# order_action_values = ['BUY', 'SELL', 'BUY_TO_COVER', 'SELL_SHORT']
# price_types_values = ['MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT', 'MARKET_ON_CLOSE']
# market_session_values = ['REGULAR', 'EXTENDED']
# order_term_values = ['GOOD_UNTIL_CANCEL', 'GOOD_FOR_DAY', 'IMMEDIATE_OR_CANCEL', 'FILL_OR_KILL']
# routing_destinations_values = ['AUTO', 'ARCA', 'NSDQ', 'NYSE']

# Reference number generated by developer. Used to ensure duplicate order is not submitted.
# Value can be of 20 alphanmeric characters or less Must be unique within this account.
# Does not appear in any API responses.
# Ref: https://apisb.etrade.com/docs/api/order/api-order-v1.html#/definitions/OrderDetail
def preview_shares_order(etrade_oauth: ETradeOAuth, etrade_order: ETradeOrder, account_id_key: str, symbol: str,
                         limit_price: float, quantity: int, print_payload: bool, print_response: bool, 
                         order_type: str = 'EQ', order_action: str = 'BUY', all_or_none: bool = False,
                         client_order_id: str = str(randint(1000000000, 9999999999)), stop_price: float = 0,
                         price_type: str = 'LIMIT', market_session: str = 'REGULAR', 
                         order_term: str = 'IMMEDIATE_OR_CANCEL', routing_destination: str = 'AUTO') -> tuple[dict, int]:

    preview_order_params = {
        'PreviewOrderRequest': {
            'orderType': order_type,
            'clientOrderId': client_order_id,
            'Order': {
                'allOrNone': all_or_none,
                'priceType': price_type,
                'orderTerm': order_term,
                'marketSession': market_session,
                'stopPrice': stop_price,
                'limitPrice': limit_price,
                'routingDestination': routing_destination,
                'Instrument': {
                    'Product': {
                        'securityType': 'EQ',
                        'symbol': symbol
                    },
                    'orderAction': order_action,
                    'quantityType': 'QUANTITY',
                    'quantity': quantity,
                }
            }
        }
    }

    preview_order_data = _post_etrade_req(etrade_oauth, etrade_order, account_id_key, preview_order_params,
                                          'preview', print_payload, print_response)

    return preview_order_params['PreviewOrderRequest'], preview_order_data['PreviewOrderResponse']['PreviewIds']['previewId']
```

My `place_shares_order` function, this is similar to the above function. This takes the preview_order_params and the preview_id from the preview_shares_order function to make the equity order. It will check and display if the order of successful or not:
```python
def place_shares_order(etrade_oauth: ETradeOAuth, etrade_order: ETradeOrder, account_id_key: str,
                       preview_order_params: dict, preview_id: int, print_payload: bool,print_response: bool) -> None:

    # Insert preview_order_params and preview_id into new place_shares_order payload
    place_order_params = {'PlaceOrderRequest': preview_order_params}
    place_order_params['PlaceOrderRequest']['PreviewIds'] = {'previewId': preview_id}

    place_order_data = _post_etrade_req(etrade_oauth, etrade_order, account_id_key, place_order_params,
                                        'place', print_payload, print_response)

    order_msg_code = place_order_data['PlaceOrderResponse']['Order']['messages']['Message']['code']
    order_msg_desc = place_order_data['PlaceOrderResponse']['Order']['messages']['Message']['description'].replace('|', ' - ')

    # Order success code = 1026
    # Ref: https://apisb.etrade.com/docs/api/order/api-order-v1.html#/definitions/ErrorCodes
    if order_msg_code != '1026':
        raise ValueError(f"Order Msg Code: {order_msg_code}\n   Description: {order_msg_desc}")
    print(f"\nOrder Msg Code: {order_msg_code}\n   Description: {order_msg_desc}\n")
```

And calling them:
```python
preview_order_params, preview_id = preview_shares_order(etrade_oauth, etrade_order, account_id_key, 'CVNA',
                                                        1.00, 1, print_payload=False, print_response=False)

place_shares_order(etrade_oauth, etrade_order, account_id_key, preview_order_params,
                   preview_id, print_payload=False, print_response=False)
```

If successful your output should be:
```
Order Msg Code: 1026
Description: 200 - Your order was successfully entered during market hours.
```
You can verify even further by printing out your order history:
```python
print('Orders:', etrade_order.list_orders(account_id_key, resp_format='json'))
```

**Comment by sfcheng** [comment]
After one day of digging, I found the root cause of this stupid issue. The string key "previewIds" need be capitalized as "PreviewIds". Otherwise, the server won't recognize the previewId parameter.

**Comment by windrider09** [comment]
Looots of inconsistency in Etrade API. Sometimes the first character is capped and sometimes it isn't.

**Comment by sfcheng** [comment]
I do have another issue with etrade api. During authentication, from time to time, I got this error. All I can do is to restart the code and then it could pass without error. 

Exception has occurred: UnicodeDecodeError
'ascii' codec can't decode byte 0xe2 in position 60: ordinal not in range(128)
  File "I:\projects\EtradePythonClient\auto_trade.py", line 577, in <module>
    session = etrade.get_auth_session(request_token,
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 60: ordinal not in range(128)

**Comment by m4rkyt** [comment]
> For anyone else who comes across this thread, i was unable to get the `preview_equity_order` and `place_equity_order` functions to work but i was able to come up with this workaround.
> 
> You basically need to make the request yourself using the underlying api endpoints instead of the functions. For these function to work, you need to have already setup pyetrades oauth obj (in my case its `etrade_oauth`)
> 
> ```python
> import json
> import xmltodict
> import xml.etree.ElementTree as ET
> 
> from dicttoxml2 import dicttoxml
> 
> from pyetrade.order import ETradeOrder
> from pyetrade import ETradeAccounts, ETradeOAuth
> ```
> 
> Function for making the post requests to the etrade api endpoints
> 
> ```python
> def _post_etrade_req(etrade_oauth: ETradeOAuth, etrade_order: ETradeOrder, account_id_key: str,
>                      order_params: dict, post_endpoint: str, print_payload: bool, print_response: bool) -> dict:
> 
>     order_payload = dicttoxml(order_params, root=False, attr_type=False).decode('UTF-8')
> 
>     if print_payload:
>         pretty_xml = ET.XML(order_payload)
>         ET.indent(pretty_xml)
>         print(f'\n{post_endpoint.capitalize()} Order Request XML Payload:\n{"="*(27+len(post_endpoint))}\n'
>               f'{ET.tostring(pretty_xml, encoding="unicode")}')
> 
>     headers = {"consumerKey": etrade_oauth.consumer_key, 'Content-Type': 'application/xml'}
>     post_endpoint_url = f'https://api.etrade.com/v1/accounts/{account_id_key}/orders/{post_endpoint}'
> 
>     order_response = etrade_order.session.post(post_endpoint_url, headers=headers, data=order_payload)
> 
>     order_data = json.loads(json.dumps(xmltodict.parse(order_response.text)))
>     
>     if print_response:
>         print(f'\n{post_endpoint.capitalize()} Order JSON Response:\n{"="*(21+len(post_endpoint))}\n'
>               f'{json.dumps(order_data, indent=4)}')
> 
>     return order_data
> ```
> 
> My `preview_shares_order` function - this returns the preview_order_params and the preview_id from the preview_order_response:
> 
> ```python
> # order_action_values = ['BUY', 'SELL', 'BUY_TO_COVER', 'SELL_SHORT']
> # price_types_values = ['MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT', 'MARKET_ON_CLOSE']
> # market_session_values = ['REGULAR', 'EXTENDED']
> # order_term_values = ['GOOD_UNTIL_CANCEL', 'GOOD_FOR_DAY', 'IMMEDIATE_OR_CANCEL', 'FILL_OR_KILL']
> # routing_destinations_values = ['AUTO', 'ARCA', 'NSDQ', 'NYSE']
> 
> # Reference number generated by developer. Used to ensure duplicate order is not submitted.
> # Value can be of 20 alphanmeric characters or less Must be unique within this account.
> # Does not appear in any API responses.
> # Ref: https://apisb.etrade.com/docs/api/order/api-order-v1.html#/definitions/OrderDetail
> def preview_shares_order(etrade_oauth: ETradeOAuth, etrade_order: ETradeOrder, account_id_key: str, symbol: str,
>                          limit_price: float, quantity: int, print_payload: bool, print_response: bool, 
>                          order_type: str = 'EQ', order_action: str = 'BUY', all_or_none: bool = False,
>                          client_order_id: str = str(randint(1000000000, 9999999999)), stop_price: float = 0,
>                          price_type: str = 'LIMIT', market_session: str = 'REGULAR', 
>                          order_term: str = 'IMMEDIATE_OR_CANCEL', routing_destination: str = 'AUTO') -> tuple[dict, int]:
> 
>     preview_order_params = {
>         'PreviewOrderRequest': {
>             'orderType': order_type,
>             'clientOrderId': client_order_id,
>             'Order': {
>                 'allOrNone': all_or_none,
>                 'priceType': price_type,
>                 'orderTerm': order_term,
>                 'marketSession': market_session,
>                 'stopPrice': stop_price,
>                 'limitPrice': limit_price,
>                 'routingDestination': routing_destination,
>                 'Instrument': {
>                     'Product': {
>                         'securityType': 'EQ',
>                         'symbol': symbol
>                     },
>                     'orderAction': order_action,
>                     'quantityType': 'QUANTITY',
>                     'quantity': quantity,
>                 }
>             }
>         }
>     }
> 
>     preview_order_data = _post_etrade_req(etrade_oauth, etrade_order, account_id_key, preview_order_params,
>                                           'preview', print_payload, print_response)
> 
>     return preview_order_params['PreviewOrderRequest'], preview_order_data['PreviewOrderResponse']['PreviewIds']['previewId']
> ```
> 
> My `place_shares_order` function, this is similar to the above function. This takes the preview_order_params and the preview_id from the preview_shares_order function to make the equity order. It will check and display if the order of successful or not:
> 
> ```python
> def place_shares_order(etrade_oauth: ETradeOAuth, etrade_order: ETradeOrder, account_id_key: str,
>                        preview_order_params: dict, preview_id: int, print_payload: bool,print_response: bool) -> None:
> 
>     # Insert preview_order_params and preview_id into new place_shares_order payload
>     place_order_params = {'PlaceOrderRequest': preview_order_params}
>     place_order_params['PlaceOrderRequest']['PreviewIds'] = {'previewId': preview_id}
> 
>     place_order_data = _post_etrade_req(etrade_oauth, etrade_order, account_id_key, place_order_params,
>                                         'place', print_payload, print_response)
> 
>     order_msg_code = place_order_data['PlaceOrderResponse']['Order']['messages']['Message']['code']
>     order_msg_desc = place_order_data['PlaceOrderResponse']['Order']['messages']['Message']['description'].replace('|', ' - ')
> 
>     # Order success code = 1026
>     # Ref: https://apisb.etrade.com/docs/api/order/api-order-v1.html#/definitions/ErrorCodes
>     if order_msg_code != '1026':
>         raise ValueError(f"Order Msg Code: {order_msg_code}\n   Description: {order_msg_desc}")
>     print(f"\nOrder Msg Code: {order_msg_code}\n   Description: {order_msg_desc}\n")
> ```
> 
> And calling them:
> 
> ```python
> preview_order_params, preview_id = preview_shares_order(etrade_oauth, etrade_order, account_id_key, 'CVNA',
>                                                         1.00, 1, print_payload=False, print_response=False)
> 
> place_shares_order(etrade_oauth, etrade_order, account_id_key, preview_order_params,
>                    preview_id, print_payload=False, print_response=False)
> ```
> 
> If successful your output should be:
> 
> ```
> Order Msg Code: 1026
> Description: 200 - Your order was successfully entered during market hours.
> ```
> 
> You can verify even further by printing out your order history:
> 
> ```python
> print('Orders:', etrade_order.list_orders(account_id_key, resp_format='json'))
> ```

**Comment by m4rkyt** [comment]
Hi, I've been trying to automate some options trades using pytrade/etrade for some months and while I can get individual legs to excersise, there doesn't seem to be support for spreads using pyetrade. Hense I've been looking at your code example here and trying to modify that to suit my needs. Starting with the code as is, I don't seem able to get passed the etrade_oauth part. I see NameError: name 'etrade_oauth' is not defined. Did you mean: 'ETradeOAuth'? Would anyone be able to help me integrate the above code into Jesse's original outh example ?

**Comment by jessecooper** [comment]
@Robert-Zacchigna Looks like there is a short coming in the pyetrade lib that is corrected by your function. Would you mind opening up a PR that would add your method to the ETradeOrder object? That would be very appreciated I am sure by everyone in the community.

**Comment by m4rkyt** [comment]
Thanks @Robert-Zacchigna that's working fine now for equity orders ! I will modify the fields to support Options orders insteadf of Equity orders and hopefully eventually get a spread to work also. Much apprecaited.

**Comment by Robert-Zacchigna** [comment]
@m4rkyt No problem, glad you were able to make it work.

@jessecooper I'd be happy to, i haven't looked too deeply into the source code so it might take a little to get up to speed. By method do you mean `_post_etrade_req` or do you mean a fix for the `preview_equity_order` and `place_equity_order` functions in order.py?

**Comment by jessecooper** [comment]
> @m4rkyt No problem, glad you were able to make it work.
> 
> @jessecooper I'd be happy to, i haven't looked too deeply into the source code so it might take me a little bit to get up to speed. By method do you mean `_post_etrade_req` or do you mean a fix for the `preview_equity_order` and `place_equity_order` functions in `order.py`?

The fix for `preview_equity_order` and `place_equity_order` in `order.py`

**Comment by jessecooper** [comment]
I do agree. The `orders.py` module is actually fairly older code and is not following the same patterns as refactored modules like the `accounts.py` module. 
The newer modules all use `xmltodict` (https://github.com/jessecooper/pyetrade/blob/master/pyetrade/accounts.py#L10) and all methods are defaulted to `xml` (https://github.com/jessecooper/pyetrade/blob/master/pyetrade/accounts.py#L61). 
Like you have noticed the `json` support is spotty for whatever reason in the ETrade API. I have been meaning to refactor all modules to follow this new pattern and use type hints where possible. I agree with all your above assertions and would really appreciated the contribution and modernization of that orders module. Thanks in advance.

**Comment by Robert-Zacchigna** [comment]
@jessecooper Sounds good, I've given it all a first run through, please check it out here and let me know what you think: https://github.com/jessecooper/pyetrade/pull/78

**Comment by jessecooper** [comment]
@Robert-Zacchigna Thank you for doing this. Give me a bit of time to look at the changes.

**Comment by m4rkyt** [comment]
Hi @mw66,
Currently my code still places all option legs individually and waits for confirmation on long fills before placing the short since my account won't let me trade naked shorts. It's a bit messy doing this as I can lose a few seconds waiting for confirmation of a fill so I do plan to modify this to use a spread. I will try this over the next couple of weeks and report back.

**Comment by windrider09** [comment]
> > ... hopefully eventually get a spread to work also.
> 
> @m4rkyt are you able to get the spread to work? can you create a PR to share the code?

I'd love to see the spread order to work too.

**Comment by korivernon** [comment]
Hi all, I'm new here. I'm trying to call the `preview_equity_order` method along with the `place_equity_order` method. I have a pretty lengthy question with two parts (1 is for options order, 2 is for equity order). I'm sure I'm doing something wrong somewhere and I'd appreciate some assistance with order functionality!


1) I attempted to place an **option order** but I get the following response:

```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.etrade.com', port=443): Read timed out.
```
Below is what I pass in to preview_equity_order
```
etrade_order.preview_equity_order(
        securityType="OPTN",
        orderType="OPTN",
        accountIdKey="XXXXXXXXXXXXXX",
        symbol="BAC",
        orderAction="SELL_CLOSE",
        clientOrderId="6591041807",
        priceType="MARKET",
        quantity=3,
        callPut="CALL",
        expiryDate=datetime.datetime(2023,4,21), # modified to take datetime object
        marketSession="REGULAR",
        orderTerm= "GOOD_FOR_DAY",
        strikePrice=30
    )
```
Here is the Payload
```
{ 
'PreviewOrderRequest': {
      'orderType': 'OPTN', 
      'clientOrderId': '6591041807', 
      'Order': {
            'securityType': 'OPTN', 
            'orderType': 'OPTN', 
            'accountIdKey': 'zBRmF6b_gzE-mkO74Vbaag', 
            'symbol': 'BAC', 
            'orderAction':  'SELL_CLOSE', 
            'clientOrderId': '6591041807', 
            'priceType': 'MARKET', 
            'quantity': 3, 
            'callPut': 'CALL', 
            'marketSession': 'REGULAR', 
            'orderTerm': 'GOOD_FOR_DAY', 
            'strikePrice': 30, 'Instrument': {
                        'Product': {
                              'securityType': 'OPTN', 
                              'symbol': 'BAC', 
                              'expiryDay': 21, 
                              'expiryMonth': 4, 
                              'expiryYear': 2023, 
                              'callPut': 'CALL', 
                              'strikePrice': 30
                                    }, 
                        'orderAction': 'SELL_CLOSE', 
                        'quantityType': 'QUANTITY', 
                        'quantity': 3
                  }
            }
      }
}
```

2) Also having an issue when trying to place an **equity order.** 
```
etrade_order.preview_equity_order(
        securityType="EQ",
        orderType="EQ",
        accountIdKey="XXXXXXXXXXXXXX",
        symbol="AAPL",
        orderAction="SELL",
        clientOrderId="6591041907",
        priceType="MARKET",
        quantity=1,
        marketSession="REGULAR",
        orderTerm="GOOD_FOR_DAY",
    )
```
Below is the preview order request.
```
{
'PreviewOrderRequest':  {
      'orderType': 'EQ', 
      'clientOrderId': '6591041907', 
      'Order': {
            'securityType': 'EQ', 
            'orderType': 'EQ', 
            'accountIdKey': 'XXXXXXXXXXXXXXX, 
            'symbol': 'AAPL', 
            'orderAction': 'SELL', 
            'clientOrderId': '6591041907', 
            'priceType': 'MARKET', 
            'quantity': 1, 
            'marketSession': 'REGULAR', 
            'orderTerm': 'GOOD_FOR_DAY', 
            'Instrument': {
                  'Product': {
                        'securityType': 'EQ', 
                        'symbol': 'AAPL'
                  }, 
            'orderAction': 'SELL', 
            'quantityType': 'QUANTITY', 
            'quantity': 1
                  }
            }
      }
}
```

I get the following response: 
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.etrade.com', port=443): Read timed out.
```

Thanks for taking a look!
-Kori

**Comment by Robert-Zacchigna** [comment]
@korivernon I havent seen that error before, could be something with your network or something else. 

- Are you able to make other calls with the api?
- Did you try this during trading hours or after hours?
- Furthermore, one of the weird quirks of the API is that it wont let you preview or attempt to place an equity order if the order itself is more than the available cash you have to spend in your account. Don't know why it is that way, just something I've observed during my usage with the API. 
    - Although that would usually kick out a different error than the one above (which is why i think it could be something with your network connection).

**Comment by korivernon** [comment]
Hey Robert! Thank you for your reply.
1) Yes, I'm able to make other calls with the API. I actually tried implementing the order functionality on my own before stumbling upon this repository.

I successfully previewed an order with my implementation, however, I was unable to place the order. I received the error I received the error that said something along the lines of: "we were unable to place your order as we think you placed it by mistake. Please resubmit if it wasn't a mistake."

2) I did try to place it outside of market hours... maybe that's the issue?!

3) I ran this with shares that I already have. Maybe it's a network issue; I'll try again tomorrow during Market hours.

Thanks, Robert!

**Comment by korivernon** [comment]
I'm still getting an issue trying to submit my order (using my own order version) during market hours... Successfully Previews but I get this 
```
Error: For your protection, we have timed out your original order request. If you would like to place this order, please resubmit it now.
```

When I use the order functionality from EtradeOrder, I get this issue:
```
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 4
```

Does anyone mind sending their `kwargs` with sensitive information redacted? Below are mine for an options order. **I modified to take in datetime object**
```
{'securityType': 'OPTN', 'orderType': 'OPTN', 'accountIdKey': 'XXXXXXXXXXX', 'symbol': 'BAC', 'orderAction': 'SELL_CLOSE', 'clientOrderId': '6591041807', 'priceType': 'MARKET', 'quantity': 3, 'callPut': 'CALL', 'expiryDate': datetime.datetime(2023, 4, 21, 0, 0), 'marketSession': 'REGULAR', 'orderTerm': 'GOOD_FOR_DAY', 'strikePrice': 30}
```

Thanks, 
Kori

**Comment by Robert-Zacchigna** [comment]
@korivernon I think you might be missing some params, try adding these 3 params as well to your kwargs:
```python
"allOrNone": False, "stopPrice": 0, "routingDestination": 'AUTO'
```
The etrade api uses a mix of json and xml endpoints (who knows why), so the error above seems to indicate the xml payload is malformed (which could be the result of missing params).

I dont have much experience with options orders but it should be similar enough to equity orders.

**Comment by korivernon** [comment]
> @korivernon I think you might be missing some params, try adding these 3 params as well to your kwargs:
> 
> ```python
> "allOrNone": False, "stopPrice": 0, "routingDestination": 'AUTO'
> ```
> 
> The etrade api uses a mix of json and xml endpoints (who knows why), so the error above seems to indicate the xml payload is malformed (which could be the result of missing params).
> 
> I dont have much experience with options orders but it should be similar enough to equity orders.

It seems like that may have done the trick! 

Sometimes the read times out. Other times it seems to execute without issue. This may be because I'm trying to place the order outside of market hours, so I'll give it another try in the morning. 

In the meantime, have you ever gotten this:
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.etrade.com', port=443): Read timed out.
```

Additionally, when it "seems to run without issue," this is the dictionary that is the result of the `preview_equity_order` function. This is not because I'm outside of market hours, as I would expect a 200 response ( 200 | The market was closed when we received your order. It has been entered into our system and will be reviewed prior to market open on the next regular trading day. After market open, please check to make sure your order was accepted.).
```
{'html': {'body': {'b': 'Http/1.1 400 Bad Request'}}}
```

Here are the kwargs I'm passing in:
```
{'securityType': 'OPTN', 
'orderType': 'OPTN', 
'accountIdKey': 'XXXXXXXXXX', 'symbol': 'BAC', 'orderAction': 'SELL_CLOSE', 'clientOrderId': '6591041807', 'priceType': 'MARKET', 'quantity': 3, 'callPut': 'CALL', 'expiryDate': datetime.datetime(2023, 4, 21, 0, 0), 'marketSession': 'REGULAR', 'orderTerm': 'GOOD_FOR_DAY', 'strikePrice': 30, 'allOrNone': False, 'stopPrice': 0, 'routingDestination': 'AUTO'}
```

**Comment by Robert-Zacchigna** [comment]
I see you mentioned using a custom order function, did you by chance specify a timeout in the request? From what i can tell its possible the timeout is being reached before the request has time to be completed.

As for the 400 error im not too sure, it strange that it happens when you call the `preview_equity_order` function directly and not when you try to place an equity as well.

I say that because if you look at the code for the order functions, `preview_equity_order` is called within the `place_equity_order` function and the `place_options_order` function calls the `place_equity_order` function.
  * Just to be clear: option_order -> place_order -> preview_order

If the order is executed then i wouldn't be too concerned about it, i would take a guess that it might be related to the timeout issue.

**Comment by genedragon** [comment]
UPDATE: appears that my VPN was playing some role here. Connecting to VPN resolved the issue.
