### ISSUE TITLE
HTTPError: 401 Client Error: Unauthorized for url: https://apisb.etrade.com/v1/accounts/list.json

### ISSUE THREAD

**Issue by spanchan** [jessecooper/pyetrade#28]
Sandbox env worked well and when switched production keys, get the error 

HTTPError: 401 Client Error: Unauthorized for url: https://apisb.etrade.com/v1/accounts/list.json

Is there setting or call that will switch dev to false?

Thanks for the work on pyetrade!

**Comment by 1rocketdude** [comment]
I'm getting same error, which is new with version 1.2 the previous version
didn't have this issue.

**Comment by spanchan** [comment]
I see. I can see param dev being passed in the accounts method in unit tests but not exposed?

**Comment by jessecooper** [comment]
In 1.2 the dev arg has been moved from the method level to the class init.

**Comment by spanchan** [comment]
Thanks Jesse.
