### ISSUE TITLE
Help wanted - getQuote

### ISSUE THREAD

**Issue by no7rosman** [jessecooper/pyetrade#30]
Hello,

I am using the following code:

symbols = ['MAXR']

list_stock_quote = pyetrade.ETradeMarket.get_quote(
    symbols=symbols,
    detail_flag=None,
    require_earnings_date=None,
    skip_mini_options_check=None,
    resp_format="xml")

print(list_stock_quote)

and getting the following error. What is it looking for for self?
 list_stock_quote = pyetrade.ETradeMarket.get_quote(
TypeError: get_quote() missing 1 required positional argument: 'self'

**Comment by jessecooper** [comment]
You need to instantiate the object ETradeMarket first. get_quote() is not a static method and needs information from the object initialization to complete the request.

**Comment by no7rosman** [comment]
This is working.

My api keys are only for the sandbox at ETrade. It appears when using the sandbox it only returns a quote for GOOG while dev=True.

quote = pyetrade.market.ETradeMarket(
    consumer_key,
    consumer_secret,
    tokens['oauth_token'],
    tokens['oauth_token_secret'],
    dev=True)
