### ISSUE TITLE
Get Select fields from Market module

### ISSUE THREAD

**Issue by sumeetagbi** [jessecooper/pyetrade#40]
Hi 
I am using Market.py and modifying it according to my needs. can I know how I can pull only few fields from api call using 
url = self.base_url + "/v1/market/quote/" + symbols + ".json"
likes of

url = self.base_url + "/v1/market/quote/fields=symbol,symbolDescrition" + symbols + ".json"

your help is much appreciated.
fields here are from standard fields available with api call one from ALL , Extended Hours etc.
attached market.py, cannot upload market.py so attached as docx
Thank you in advance

[market.docx](https://github.com/jessecooper/pyetrade/files/5859681/market.docx)

**Comment by jessecooper** [comment]
The application built with pyetrade should parse the return from the API. Modifying pyetrade to do that is not the correct way to go about that. The call in pyetrade should be aligned with etrades API documentation. If you find that it is not please reopen this issue.
