### ISSUE TITLE
stopPrice

### ISSUE THREAD

**Issue by hyungmok** [jessecooper/pyetrade#41]
https://github.com/jessecooper/pyetrade/blob/289bdb84ff0bb596f4780c13e5a57d3ab0758e51/pyetrade/order.py#L159

Hi, folks.

I have a question on the line 159. I may be wrong, but to my understanding the stopPrice is always an empty string, which means it would be useless even if I pass a stop price in the payload. Can anyone please advise me on this?

Thanks!

**Comment by rrupesh** [comment]
This is one nasty bug! :) and simple to fix. please fix this.

**Comment by jessecooper** [comment]
@rrupesh PRs are always encouraged.

**Comment by jessecooper** [comment]
fixed in 1.2.2
