### ISSUE TITLE
any1 has issues getting the request_token?

### ISSUE THREAD

**Issue by hz2018tv** [jessecooper/pyetrade#47]
pretty much failed here

        self.session = OAuth1Session(
            self.consumer_key,
            self.consumer_secret,
            callback_uri=self.callback_url,
            signature_type="AUTH_HEADER",
        )
        # get request token
        self.session.fetch_request_token(self.req_token_url)

also tried etrade official python client, also failed at this step.

**Comment by 1rocketdude** [comment]
try this instead

import pyetrade

consumer_key = 'Etrade_consumer_key'
consumer_secret ='Etrade_consumer_secret'
oauth = pyetrade.ETradeOAuth(consumer_key, consumer_secret)
print(oauth.get_request_token())
API_token = input('eTrade token: ')
oauth.get_access_token(API_token)
accounts_api = pyetrade.accounts.ETradeAccounts(consumer_key, consumer_secret, oauth.access_token['oauth_token'],
                                                oauth.access_token['oauth_token_secret'], dev=False)

**Comment by hz2018tv** [comment]
havent tried your code, but oauth.get_request_token() will do exactly
    self.session = OAuth1Session(
        self.consumer_key,
        self.consumer_secret,
        callback_uri=self.callback_url,
        signature_type="AUTH_HEADER",
    )
    # get request token
    self.session.fetch_request_token(self.req_token_url)
it has been failing for me.

**Comment by hz2018tv** [comment]
update. 
it works again without any code change after a couple of days. seems to be an etrade problem.

**Comment by hz2018tv** [comment]
seems to be an etrade problem.
