### ISSUE TITLE
order["stopPrice"] is always empty

### ISSUE THREAD

**Issue by mingwugmail** [jessecooper/pyetrade#50]
https://github.com/jessecooper/pyetrade/blob/master/pyetrade/order.py#L159
```
        order["stopPrice"] = ""
```

This line should be changed to:

```
        if "stopPrice" in kwargs:
          stopPrice = (float(kwargs["stopPrice"]) - 0.01)
          if stopPrice > 0:
            order["stopPrice"] = "%.2f" % stopPrice
```

to properly convert float number to 2 decimal place dollar value.

**Comment by jessecooper** [comment]
released in 1.2.2 @mingwugmail thank you for the contribution.
