### ISSUE TITLE
Token request failed with code 401

### ISSUE THREAD

**Issue by viaConBodhi** [jessecooper/pyetrade#52]
Anyone else getting this while attempting login? I just ran it last night and got this error. Rebooted thinking it was something simple but looks like it's not.  Looks like it hanging up on the following. Any thoughts on what's happening as things were working fine a week ago. 

self.session.fetch_request_token(self.req_token_url)
token = self._fetch_token(url, **request_kwargs)
raise TokenRequestDenied(error % (r.status_code, r.text), r)

TokenRequestDenied: Token request failed with code 401, response was '<!doctype html><html lang="en"><head><title>HTTP Status 401 – Unauthorized</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 401 – Unauthorized</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> oauth_problem=consumer_key_rejected</p><p><b>Description</b> The request has not been applied because it lacks valid authentication credentials for the target resource.</p><hr class="line" /><h3></h3></body></html>'.

**Comment by mw66** [comment]
> this is a typical problem with Etrade. Put the date on your calendar for a month before renewal so that you don't have expired 

How to do renew?  send email to their support?

**Comment by 1rocketdude** [comment]
send a secure message from within the web platform. There is a specific menu item for API keys. Use kind words, rub your lucky rabbits foot, give offerings to local deities, and within a week, it’ll just start working.

I don’t have a good sense how the API will “work” after Sept 1 switchover to Morgan Stanley…
