### ISSUE TITLE
oauth no longer working

### ISSUE THREAD

**Issue by exploringfinance** [jessecooper/pyetrade#73]
Has anyone noticed in the last two days that authentication has stopped working? When creating the oauth app and sending it, I keep getting bad request when I hit the API url: https://api.etrade.com/oauth/request_token

**Comment by ericgray** [comment]
Same here!

**Comment by exploringfinance** [comment]
Yes got it working. This can be resolved

**Comment by 1rocketdude** [comment]
uauth stopped working for me today. I crash out at fetch_access_token. I get to enter the eTrade supplied token, but then crash. Same issue, or different?

**Comment by exploringfinance** [comment]
It could be all related. I actually wrote the [etrader](https://exploringfinance.github.io/etrader/index.html) package for R and was having issues. I put in a fix that appears to be working for now. It had to do with the headers

**Comment by nathanramoscfa** [comment]
Please provide the solution you came up with.

**Comment by exploringfinance** [comment]
I had to make some updates to my R package to use proper headers and then it worked

**Comment by jessecooper** [comment]
Is this still an issue? If so, can we please get a traceback on this issue. @exploringfinance can you please post the headers that you had to apply to your R package?

**Comment by nathanramoscfa** [comment]
@jessecooper no issues here.
